import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "../components/SessionWrapper/SessionWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className="w-full flex flex-col items-center">
          <div className="w-full max-w-[1250px] relative min-h-[100dvh]">{children}</div>
        </body>
      </html>
    </SessionWrapper>
  );
}
